### PR TITLE
feat: add a solution called from_into_person_default

### PR DESCRIPTION
**Pull request by liby**
## Motivation

- `Person::default()` is easier to understand than `Default::default()`.

### CODE REVIEW

**Comment by alexxroche** [comment]
Self::default() is a third option.

**Comment by liby** [comment]
> Self::default() is a third option.

Thank you for your indulgence.

**Comment by alexxroche** [comment]
I'm comfortable with [Tim Toady](https://en.wikipedia.org/wiki/TMTOWTDI) (as long as we don't end up like PHP.)

**Comment by liby** [comment]
> I'm comfortable with Tim Toady (as long as we don't end up like PHP.)

Thanks to you, I’ve learned something no one has ever told me before

**Pull request merged**
